config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'
  resources :bathrooms, only: [:show, :new, :create]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => 'users/sessions'}

  resources :map, only: :index

  resources :bathrooms, only: :show do
    resources :reviews, only: [:new, :create]
  end

  resources :advanced, only: :new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bathroom.rb
class Bathroom < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates_presence_of :latitude,
                        :longitude

  def distance_to(lat, long)
    distance_lat = (latitude - lat) * Math::PI / 180
    distance_long = (longitude - long) * Math::PI / 180

    a = Math.sin(distance_lat / 2) * Math.sin(distance_lat / 2) +
        Math.cos(lat * Math::PI / 180) * Math.cos(lat * Math::PI / 180) *
        Math.sin(distance_long / 2) * Math.sin(distance_long / 2)

    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt((1-a).abs))

    d = 3958.8 * c

    d.round(3)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bathroom

  enum rating: %w(nil disliked liked loved), _suffix: true

  enum experience: %w(nil disliked liked loved), _prefix: :experience
  enum cleanliness: %w(nil disliked liked loved), _prefix: :cleanliness
  enum smell: %w(nil disliked liked loved), _prefix: :smell
  

end 

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end
end

app/controllers/advanced_controller.rb
class AdvancedController < ApplicationController

  def index
    @bathrooms = Bathroom.advanced_search(search_terms)
  end

  def new
    session[:advanced] = true
    @user = User.find(session[:user_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  add_flash_types :success

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] #User.last if User.all != []#
  end

  def four_oh_four
    raise ActionController::RoutingError.new('Not Found')
  end

  def require_user
    four_oh_four unless current_user
  end

end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  def show
    @bathroom = Bathroom.find(params[:id])
  end

  def new
  end

  def create
    bathroom_latitude = get_coordinates[:lat]
    bathroom_longitude = get_coordinates[:lng]
    bathroom = Bathroom.create(bathroom_params)
    bathroom.update_attributes(latitude: bathroom_latitude, longitude: bathroom_longitude)
    if bathroom.save
      redirect_to "/bathrooms/#{bathroom.id}"
    else
      flash[:error] = bathroom.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def bathroom_params
    params.permit(:name, :street, :city, :state, :accessible, :changing_table, :unisex)
  end

  def get_coordinates
    query = "#{params[:street]} #{params[:city]}, #{params[:state]} #{params[:zip]}"

    GeocodeService.new.geocall(query)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end 
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    if !current_user
      redirect_to root_path
    end

    @user = current_user
    if session[:advanced] == true && !search_terms.empty?
      @bathrooms = advanced_search(search_terms)[1..20]
      session[:advanced] = false
    else
      @bathrooms = Bathroom.all.limit(20)
    end
  end

  private

  def search_terms
    params.permit(:address, :city, :state, :zip, :distance, :accessible, :changing_table, :unisex)
  end

  def advanced_search(search_terms)
    coordinates = get_coordinates(search_terms)
    location_lat = coordinates[:lat]
    location_long = coordinates[:lng]
    distance = search_terms[:distance].to_f
    accessible = search_terms[:accessible]
    unisex = search_terms[:unisex]
    changing_table = search_terms[:changing_table]

    results = Bathroom.all.select { |bathroom|
      bathroom.distance_to(location_lat, location_long) < distance
    }

    if accessible != "nil"
      results = results.find_all { |bathroom|
        bathroom.accessible == accessible
      }
    end

    if unisex != "nil"
      results = results.find_all { |bathroom|
        bathroom.unisex == unisex
      }
    end

    if changing_table != "nil"
      results = results.find_all { |bathroom|
        bathroom.changing_table == changing_table
      }
    end

    results
  end

  def get_coordinates(search_terms)
    query = "#{search_terms[:address]} #{search_terms[:city]}, #{search_terms[:state]} #{search_terms[:zip]}"

    GeocodeService.new.geocall(query)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new 
  end 
  
  def create
    @bathroom = Bathroom.find(params[:bathroom_id])
    if field_empty?
      flash[:error] = "Please fill in all fields in order to create a review."
      redirect_to new_bathroom_review_path(@bathroom.id)
    else
      review = @bathroom.reviews.new(review_params)
      if review.save
        flash[:success] = "Review successfully created"
        redirect_to "/bathrooms/#{@bathroom.id}"
      else
        render :new
      end
    end
  end
  
  private
  
  def review_params
    old_params = params.permit(:cleanliness, :experience, :smell, :content, :purchase_required?, :well_stocked?, :cool_decor?)

    new_params = Hash.new

    new_params[:cleanliness] = old_params[:cleanliness].to_i
    new_params[:experience] = old_params[:experience].to_i
    new_params[:smell] = old_params[:smell].to_i
    new_params[:content] = old_params[:content]
    new_params[:purchase_required?] = old_params[:purchase_required?]
    new_params[:well_stocked?] = old_params[:well_stocked?]
    new_params[:cool_decor?] = old_params[:cool_decor?]
    new_params[:user_id] = current_user[:id]
    return new_params
  end

  def field_empty?
    params = review_params
    params[:cleanliness].nil? || params[:experience].nil? || params[:smell].nil?
  end

end 

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to map_index_path
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  def destroy
    reset_session

    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advanced/new.html.erb
<section id="forms">
  <div class="search">
<%= form_tag "/map", method: :get do %>
    <%= label_tag :address %><br>
    <%= text_field_tag :address, '', required: true %><br><br>

    <%= label_tag :city %><br>
    <%= text_field_tag :city, '', required: true %><br><br>

    <%= label_tag :state %><br>
    <%= text_field_tag :state, '', required: true %><br><br>

    <%= label_tag :zip %><br>
    <%= text_field_tag :zip %><br><br>

    <label for="distance">Distance from address (0.1-100 miles):</label><br><br>
    <input type="number" id="distance" name="distance"
       min="0.1" max="100" value="5.0" step="0.1">
    <br><br>
    <br><br>
    <br><br>

    Accessible?:<br>
    <select name="accessible" id="accessible" class="form-control form-control-sm">
      <option value=nil></option>
      <option value="true">true</option>
      <option value="false">false</option>
    </select>
    <br><br>

    Has Changing Table?:<br>
    <select name="changing_table" id="changing_table" class="form-control form-control-sm">
      <option value=nil></option>
      <option value="true">true</option>
      <option value="false">false</option>
    </select>
    <br><br>

    Unisex?:<br>
    <select name="unisex" id="unisex" class="form-control form-control-sm">
      <option value=nil></option>
      <option value="true">true</option>
      <option value="false">false</option>
    </select>
    <br><br>

    <%= submit_tag 'Search', class: "btn btn-primary"%>
  <% end %>
</div>
</section>

app/views/bathrooms/new.html.erb
<section id="forms">
  <div class="new-bathroom">
<%= form_tag "/bathrooms", method: :post do %>
    <%= label_tag :name %>
    <%= text_field_tag :name %><br><br>

    <%= label_tag :street %>
    <%= text_field_tag :street %><br><br>

    <%= label_tag :city %>
    <%= text_field_tag :city %><br><br>

    <%= label_tag :state %>
    <%= text_field_tag :state %><br><br>

    <%= label_tag :zip %>
    <%= text_field_tag :zip %><br><br>

    <div class="buttons">
    Accessible?:<br>
    <select name="accessible" id="accessible">
      <option value=nil></option>
      <option value="true">true</option>
      <option value="false">false</option>
    </select>
    <br><br>
    Has Changing Table?:<br>
    <select name="changing_table" id="changing_table">
      <option value=nil></option>
      <option value="true">true</option>
      <option value="false">false</option>
    </select>
    <br><br>
    Unisex?:<br>
    <select name="unisex" id="unisex">
      <option value=nil></option>
      <option value="true">true</option>
      <option value="false">false</option>
    </select>
    <br><br>
</div>
    <%= submit_tag 'Create Bathroom', class: "btn btn-primary" %>
  <% end %>
</div>
</section>

app/views/bathrooms/show.html.erb
<section align = "center" id="bathroom">
  <h4>Located: <%=  "#{@bathroom.name}" %></h4>
  <h5>Address: <%=  "#{@bathroom.street}, #{@bathroom.city}, #{@bathroom.state}" %></h5>
  <h5> Changing Table?
    <% if  @bathroom.changing_table == true %>
      yes
     <% else %>
      no
      <% end%>
  </h5>
  <h5> Accessible?
    <% if  @bathroom.accessible == true %>
      yes
     <% else %>
      no
      <% end%>
  </h5>
  <h5> Unisex?
    <% if  @bathroom.unisex == true %>
      yes
     <% else %>
      no
      <% end%>
  </h5>

</section><br>

<br><section align = "center" id = "reviews">
  <h3>Reviews</h3>
    <h6><%= link_to "Add Review", new_bathroom_review_path(@bathroom.id) %></h6>
    <%if @bathroom.reviews.empty? %>
        <h5>This bathroom has not yet been reviewed.</h5>
    <% else %>
      <section class = "list-reviews">
        <% @bathroom.reviews.each do |review| %>
          <section id= 'review-<%=review.id%>'>
            <h6> Purchase Required?:
              <% if  review.purchase_required? == true %>
                yes
              <% else %>
                no
                <% end%>
            </h6>
            <h6> Well Stocked?:
              <% if  review.well_stocked? == true %>
                yes
              <% else %>
                no
                <% end%>
            </h6>
            <h6> Cool Decor?:
              <% if  review.cool_decor? == true %>
                yes
              <% else %>
                no
                <% end%>
            </h6>
           <h5>Review's Notes:</h5><h6><%= review.content %></h6>
          </section>
        <% end %>
      </section>
    <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gottago</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/map/index.html.erb
<section>
<div class="map-list-view">
<div id="map" float="left" style="height: 600px; width: 800px; padding: 20px;">
   <script>
     var map;
     var marker;
     var lat;
     var long;
     function initMap() {
       fetch("https://www.googleapis.com/geolocation/v1/geolocate?key=<%= ENV['GOOGLE_API_KEY'] %>", {
         method: 'POST',
       })
       .then((response) => response.json())
       .then((data) => {
         console.log(data.location)
         lat = data.location.lat;
         $("#lat").html(lat);
         long = data.location.lng;
         $("#lng").html(long);

         // window.open("/map?lat="+lat+"&long="+long,"_self");
         // // window.opener = null;
         // window.close;

         map = new google.maps.Map(document.getElementById('map'), {
           center: {lat: lat , lng: long },
           zoom: 13
         });
         var image = 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png';
         var marker = new google.maps.Marker({
            position: {lat: lat, lng: long },
            map: map,
            draggable: true,
            animation: google.maps.Animation.DROP,
            icon: image,
            title: 'You are here'
          });
        marker.setMap(map);
        marker.addListener('click', toggleBounce);
        setMarkers(map);
      })
    }
     function toggleBounce() {
        if (marker.getAnimation() !== null) {
          marker.setAnimation(null);
        } else {
          marker.setAnimation(google.maps.Animation.BOUNCE);
        }
      };

      var bathrooms = <%=raw @bathrooms.to_json%>;

    function setMarkers(map){
      for (var i = 0; i < bathrooms.length; i++) {
        var bathroom = bathrooms[i];
        var marker2 = new google.maps.Marker({
          position: {lat: bathroom.latitude, lng: bathroom.longitude},
          map: map,
          title: bathroom.name
        });
      }

      marker2.addListener('click', toggleBounce);
    }
   </script>
   <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY']%>&callback=initMap"
   async defer></script>
   </div>
  <div class="list-results" id="bathroom" float="right" style="padding-left:10px">
    <h3>Bathrooms Near You</h3>
    <ul>
      <% @bathrooms.each do |bathroom| %>
        <li id=" <%= bathroom.id%> ">
          <%=bathroom.name%>
          <a> <%= link_to "More Info", "bathrooms/#{bathroom.id}" %></a>
          <%= link_to "Get Directions", "https://www.google.com/maps/dir/?api=1&origin=my+location&destination=#{bathroom.latitude}+#{bathroom.longitude}&travelmode=walking" %>
        </li>
      <% end %>
    </ul>
  </div>
<section class="popup">
  <div class="bathroom-show">
    <h3 id="popup-name">Popup!</h3>
    <a id="popup-street">Popup!</a>
    <a id="popup-city">Popup!,</a>
    <a>, </a>
    <a id="popup-state">Popup!</a>
  </div>
</section>
</div>
</section>


  <!-- <script>
    var bathroom_id;
    let check = document.querySelector('#bathroom');
    let popup = document.querySelector('.popup');

    check.addEventListener('click', function(e){
      var bathrooms = <%=raw @bathrooms.to_json%>;
      var bathroom_id = e.target.id;
      let bathroom =  bathrooms.find(bathroom => {
        return bathroom.id == bathroom_id
      })
      console.log(bathroom)
      $("#popup-name").html(bathroom.name)
      $("#popup-street").html(bathroom.street)
      $("#popup-city").html(bathroom.city)
      $("#popup-state").html(bathroom.state)
      $("#popup-access").html(bathroom.accessible)
      $("#popup-unisex").html(bathroom.unisex)
      $("#popup-changing").html(bathroom.changing_table)
      popup.id = e.target.id
      popup.style.display = "block"
    });
  </script> -->

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <img src="https://thumbs.gfycat.com/CraftyBrokenGoldfinch-max-1mb.gif" width="30" height="30" alt="GottaGo">
  </a>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
   <div class="navbar-nav">
     <% if current_user %>
      <a class="nav-item nav-link active" href="/map">Map <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/advanced/new">Advanced Search</a>
      <a class="nav-item nav-link" href="/bathrooms/new">Add Bathroom</a>
     <% end %>
   </div>
 </div>
   <div class="user-info" align="right">
     <form class="form-inline">
    <div style="padding-left: 10px;">
      <% if current_user.nil? %>
      <a class="btn btn-outline-success"
        <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class: 'fb-login' %>
      </a>
      <% else %>
      <a class="btn btn-outline-primary"
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      </a>
    </div>
    <br>
    <br>
     <a class="fb-user-info" style="padding-left:10px">
       <%= current_user.name %>
       <%= image_tag(current_user.image) %>
     </a>
     <% end %>
   </form>
   </div>
</nav>

app/views/reviews/new.html.erb
<section align = "center" id="bathroom">
<%= form_tag bathroom_reviews_path, method: :post do %>
    <br>
  Was a purchased required in order to access the restroom?<br>
    <select name="purchase_required?" id="purchase_required?">
      <option value=nil></option>
      <option value= "true" >yes</option>
      <option value= "false">no</option>
    </select><br>
    <br>
    How did you feel about the bathroom's cleanliness<br>
    <select name="cleanliness" id="cleanliness">
      <option value=nil></option>
      <option value= 1 >Disliked</option>
      <option value= 2 >Liked</option>
      <option value= 3 >Loved</option>
    </select>
    <br><br>
  How did you feel about the bathroom's smell?<br>
    <select name="smell" id="Smell">
      <option value=nil></option>
      <option value= 1 >Disliked</option>
      <option value= 2 >Liked</option>
      <option value= 3 >Loved</option>
    </select><br>
    <br>
  Did this bathroom have nice style?<br>
    <select name="cool_decor?" id="cool_decor?">
      <option value=nil></option>
      <option value= "true" >yes</option>
      <option value= "false">no</option>
    </select><br>
    <br>
  How was your experience?<br>
  <select name="experience" id="experience">
    <option value=nil></option>
    <option value= 1 >Disliked</option>
    <option value= 2 >Liked</option>
    <option value= 3 >Loved</option>
  </select>
  <br>

  Was it well stocked?<br>
    <select name="well_stocked?" id="well_stocked?">
      <option value=nil></option>
      <option value= "true" >yes</option>
      <option value= "false">no</option>
    </select><br>

    <br><%= label_tag "Additional Notes?" %><br>
    <%= text_field_tag :content %><br>
    <br><br>
    <%= submit_tag 'Submit Review' %>
  <% end %>
</section>

app/views/welcome/show.html.erb
<section class='welcome'>
  <h1 class='welcome-msg'>Welcome to Gotta Go!</h1>
</section>